### ISSUE TITLE
Editor: Support insert and del keys from numpad

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#353]
The editor should also respect the insert and delete keys from the numpad, because those seem to be ignored, no matter if num lock is on.

Related: #157
##

**Comment by cxong** [comment]
I'm not sure if this is an SDL 1.2 bug, but it appears that num lock state is broken; the game always thinks numlock is off at the start, so if the game is started with numlock on, the numlock state will be flipped. Because of this, I think it'll be too much trouble fixing this issue. Perhaps SDL2 fixes this, or maybe there are platform-specific methods to get the current numlock state.
