### ISSUE TITLE
Network deathmatch crash + temple of carnage test

### ISSUE THREAD

**Issue by ghost** [cxong/cdogs-sdl#464]
@cxong:
Violation of the assertion

cdogs-sdl: /home/username/Projekte/cdogs-sdl/src/cdogs/actors.c:578: ActorReplaceGun: Assertion `rg.GunIdx < a->guns.size + 1' failed.

And the other computer got a crash about an adress boundary error at the end of the game which might be related.

And while we're at it: My other tester said that it would be good to make mines explode when being shot at. Do you think that's possible and/or feasible?

**Comment by cxong** [comment]
I can't really imagine a cause for this bug; I've added some logging/assertions which might help, you'll need to run using debug logging (`--log=DEBUG`). If you can remember what was happening just before the crash, or reproduce it, that would help too.

Having mines explode isn't possible because bullets don't collide with each other. It could be done with some rework, but the effort may not be worth it.

**Comment by sauer2** [comment]
@cxong I'll try next time. Unfortunately I don't know when that will be. The first crash (that crashed the joining client) happened when one of us (I think the joining client) picked up a weapon.

>Having mines explode isn't possible because bullets don't collide with each other. It could be done with some rework, but the effort may not be worth it.

Probably not. I just reduced the number of mine pickups instead and changed the skull weapon icon in the version I sent you.

If there are still too many mines, I'll probably tune up the fire rate.
