### ISSUE TITLE
Randomly spawning weapons

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#493]
At least in deathmatch mode it appears that sometimes random weapons are spawned at random places. Is this intentional?

**Comment by cxong** [comment]
yes; this is part of #367 but we didn't think through all the consequences. I imagine it could be bad if it randomly spawned a very powerful weapon that is supposed to be well hidden in a deathmatch map. There's several ways to address this problem though, depending on what you want.

**Comment by sauer2** [comment]
More problematic: It doesn't spawn the custom weapons belonging to the map but the standard weapons, like Powergun etc.

**Comment by cxong** [comment]
ok I think it makes sense to avoid spawning weapons that aren't available in the weapon selection screen.
But does this make sense at all in deathmatch/PVP modes? Some of them rely on weapon spawners and have very few starter weapons, which means the weapons that are randomly spawned are probably useless. What about disabling random spawning of items in PVP modes altogether?

**Comment by sauer2** [comment]
>What about disabling random spawning of items in PVP modes altogether?

Hard to say, since I don't get to play PVP very often. It probably also depends on how well balanced a map is. Is making it an option an option?

**Comment by cxong** [comment]
Sure; other options would also be useful: #495

**Comment by sauer2** [comment]
@cxong The game still seems to spawn ammo that isn't used by any weapon in a mission.

**Comment by cxong** [comment]
The ammo issue is a bit harder to deal with; a mission could have starter weapons, pickups, and those dropped by enemies. Maybe map objects should only drop ammo that the player who destroyed them is using? I'm not sure what the best solution is at the moment. The whole ammo system right now is underdesigned and mostly a hack. A good ammo system should be carefully designed so that the player neither gets too little nor too much ammo. I'll have to revisit the ammo system some time, like maybe when I look at the cyberdogs reimplementation #71 and add buy/sell functions. I feel like there's too many kinds of ammo, and the player should only have to worry about 2 or 3 kinds at a time, plus very rare ammo. So for example a single mission might have lots of bullets (plentiful, weak ammo), some shotgun shells (can't be wasteful, moderately powerful), and very occasionally some grenades or rockets.
