### ISSUE TITLE
Improved gun pickup and swapping

### ISSUE THREAD

**Issue by ghost** [cxong/cdogs-sdl#513]
Before some change it was possible to pick guns the player already had up and get more ammunition, but now it appears that nothing happens.
Ideally in this case was probably auto-pickup as it happens for ammunition.

**Comment by cxong** [comment]
Yes this is intentional, but can be improved. You can only pickup the same guns if they would add ammo.

I think to make this clearer we can let any gun be picked up, but say:
- If swapping guns, the player drops the gun it's replacing
- If already enough ammo, the player picks up the gun and drops the same gun again
