### ISSUE TITLE
Condensed HUD

### ISSUE THREAD

**Issue by ghost** [cxong/cdogs-sdl#515]
![hud_bug](https://user-images.githubusercontent.com/2904634/28442418-8243966a-6db0-11e7-8d54-108edcf2a7be.png)

**Comment by cxong** [comment]
This one is hard to fix properly. Guns with long names + ammo will take a lot of space, so I don't think it makes sense to simply widen the gauge to fit.

The resolution of C-Dogs is very small (minimum 320x240) so we don't want to crowd out a chunk of the screen for the HUD either.

Maybe it will help to remove the total ammo count? Since that information is implied with the new ammo gauge.

Cyberdogs didn't show the gun name at all, but then all guns had unique icons, which is not guaranteed with the custom missions.

It would be best to look at a HUD redesign. In general I would prefer making the HUD more diegetic, which would help avoid clutter. Maybe do some research into how low-resolution games did these HUDS, similar to what was done in #80 ?

**Comment by sauer2** [comment]
Maybe place the gun icon with the ammo count under the gun name?
But yeah, 

     Maybe do some research into how low-resolution games did these HUDS, 

is probably the best option.

**Comment by cxong** [comment]
It seems most low-resolution games either have a dedicated HUD section or extremely condensed text/icons. Most have super-condensed or no text at all.

Doom:
![image](https://user-images.githubusercontent.com/1083215/49350613-b517d280-f703-11e8-9b27-959ea4b248e2.png)

Duke Nukem 64 multiplayer:
![image](https://user-images.githubusercontent.com/1083215/49350635-c365ee80-f703-11e8-9352-409d906fcdff.png)

Turok rage wars:
![image](https://user-images.githubusercontent.com/1083215/49350726-3c654600-f704-11e8-82a8-26f70b3eb317.png)

Goldeneye 64:
![image](https://user-images.githubusercontent.com/1083215/49350754-56068d80-f704-11e8-88c7-dd9f9e8cfb8d.png)

The information shown is the bare minimum. We could copy these tricks and show the bare minimum of information:

- Require unique gun icons (autogenerate them if unavailable?)
- Gun models #14
- Hide player name (show in-game instead?)
- Hide score/cash unless it changed recently
- Hide health/lives unless it changed recently or low health
- Only show gun icon + ammo count in HUD
  - Don't show max ammo

**Comment by cxong** [comment]
HUD has been condensed with some elements auto hiding after inactivity, but now the HUD looks really sparse. Should give it a redesign entirely.

**Comment by cxong** [comment]
![newhud](https://user-images.githubusercontent.com/1083215/52556775-a3f4eb80-2e41-11e9-96f7-10c48eceb228.gif)

**Comment by cxong** [comment]
well looks like this is obsoleted by #594
