### ISSUE TITLE
Game refuses to run on Windows

### ISSUE THREAD

**Issue by Epictyphlosion** [cxong/cdogs-sdl#636]
Every time I try to run the game I get the following error:
"The procedure entry point SDL_RWclose could not be located in the dynamic link library C:\Program Files (x86)\C-Dogs SDL\bin\cdogs-sdl.exe."

I'm not sure if there's something that I have to install that I'm missing, but since it's related to SDL, then someone screwed up really badly when compiling this or something

**Comment by cxong** [comment]
The dlls included in 0.7.2 are the wrong version; this will be fixed in the next release
In the meantime if you download the following dlls and copy into the /bin directory this should work:
http://www.libsdl.org/release/SDL2-2.0.10-win32-x86.zip
http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5-win32-x86.zip
https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x86.zip
