### ISSUE TITLE
Tiny weapon pickup issue

### ISSUE THREAD

**Issue by chack05** [cxong/cdogs-sdl#660]
Suppose you have weapon A and B, A being equipped. Now you attempt to pick up weapon B. What happens is:

* Weapons are switched, which is the best option since there is no dual wielding.
* However, the drop/pickup code acts as if you now have two B weapons, turning the weapon on the floor into weapon A.

Basically, you have turned a B weapon into an A weapon.

**EDIT:** Reported for 0.9.1

**Comment by JonDegn** [comment]
I'm willing to try to take a look at this...

Is the following the expected behavior?
- Switch to weapon B
- If there is an ammo deficit, fill ammo to default amount
- Remove weapon from ground

**Comment by chack05** [comment]
I'd think so, but when in doubt, better ask @cxong 

That being said, should the weapon always removed from the ground? As opposed to, only if ammo is activated for this campaign?

**Comment by cxong** [comment]
Thanks for the fix! I've included it for now. However I think weapon pickups shouldn't be destroyed without replacement. The reason is to avoid co-op players competing for gun pickups.

Therefore, given player has guns A and B, and has A equipped, when they pick up gun B, they should switch to gun B and drop gun B again. The current fix destroys the gun pickup.
